<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Projects</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="css/forms.css">
    <link rel="stylesheet" href="css/main.css">
    <link rel="stylesheet" href="css/nav.css">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body class="approved">
    <?php 
        session_start();
        $currentPage = "ideas";
        include("includes/nav.php");

        include_once "includes/connection.php";
        $conn = new Database();
        $dbase = $conn->connect();

        $sql = "SELECT * FROM `project` WHERE `project_id`=".$_GET['id'];
        $result = $dbase->query($sql);
        $row = $result->fetch_assoc();
    ?>
    <div class="project-form top">
        <h1 class="main-title"><?php echo $row["project_name"]; ?></h1>
        <p>You are ready to get some funding for that dream</p>        

        <div class="progress progress2" id="slider" style="height: 6px;">
            <div class="progress-bar bg-success" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">
                <div class="leftdot3"></div>
                <div class="rightdot3"></div>
            </div>
        </div>
        <label for="slider" class="form-label">Details</label>
        <label for="slider" class="form-label right">Cash Flows</label>
    </div>
    <div style="display: flex; justify-content: center;">
        <div class="row justify-content-center a-content">
            <div class="col-6 l-side-box" style="margin-right: 2%;">
                <div>
                    <h5><b>Quick Figures Digest</b></h5>
                    <hr>
                </div>

                <div class="row">
                    <div class="form-group col-md-4">
                        <label for="form_name">Needed Capital</label>
                        <p>Money needed to pay for project purchases</p>
                    </div>
                    <div class="form-group col-md-4 ml-auto">
                        <p>$ <span id="amount"><?php echo $row["capital"];?> </span></p>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-4">
                        <label for="form_name">Payback Period</label>
                        <p>Time it takes for money generated by project to reach investments</p>
                    </div>
                    <div class="form-group col-md-4 ml-auto">
                        <p><?php echo $row["payback_p"];?></p>
                    </div>
                </div>
                <div>
                    <h4 style="padding: 0;">Business Summary</h4>
                    <ul>
                        <li><b>Project Name:</b> &emsp; <?php echo $row["project_name"]; ?></li>
                        <li><b>Industry Type:</b> &emsp; <?php echo $row["industry_type"]; ?></li>
                        <li><b>Brief Description:</b> &emsp; <?php echo $row["p_description"]; ?></li>
                        <li><b>Email Address:</b> &emsp; 
                            <span> <?php echo $row["email"]; ?></span></li>
                            <input type="hidden" value="<?php echo $_SESSION["email"]; ?>" id='email'>
                        <li><b>Contact:</b> &emsp;<span id='contact'> <?php echo $_SESSION["contact"]; ?></span></li>
                        <p></p>
                        <!-- <li><b>Contact (Mobile Number):</b> &emsp; <?php //echo $row["contact"]; ?></li> -->
                    </ul>
                    <button class="btn btn-success btn-lg btn-block" onclick="payWithPaystack()" style="border-radius: 100px;">Fund with Paystack</button>
                </div>
                
            </div>
            <div class="r-side-box col-3">
                <h4>Status: Approved</h4>
                <br>
                <p>After calculating the underlying values of your project, it is deemed viable and approved for funding.</p>
            </div>
        </div>
    </div>
    <script src="https://js.paystack.co/v1/inline.js"></script>
    <script>
        function payWithPaystack() {
            var em = $('#email').val();
            console.log(em);
          let handler = PaystackPop.setup({
            key: 'pk_test_799097618d614512de920a18fca5a294036f30f4', // Replace with your public key
            email: em,
            currency: "GHS",
            amount: $('#amount').html() * 100,
            // label: "Optional string that replaces customer email"
            onClose: function(){
              alert('Window closed.');
            },
            callback: function(response){
              let message = 'Payment complete! Reference: ' + response.reference;
              
              console.log(response.reference);
              alert(message);
            }
          });
          handler.openIframe();
        }
        //obtained from https://paystack.com/docs/payments/accept-payments/#popup
    </script>
    

    

    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js"></script>
    <script src="assets/js/script.js"></script>
</body>
</html>